### ISSUE TITLE
Error when working with Docker 1.7

### ISSUE THREAD

**Issue by iMax-pp** [docktor/docktor#103]
When creating a service on a machine with docker 1.7 installed, the following error is logged:
```
ERR createContainer
{ [Error: HTTP code is 500 which indicates error: server error - json: cannot unmarshal string into Go value of type int64
]
  reason: 'server error',
  statusCode: 500,
  json: 'json: cannot unmarshal string into Go value of type int64\n' }
#################
```

**Comment by fsamin** [comment]
Check npm dockerode dependency

**Comment by iMax-pp** [comment]
Indeed, with an update of `dockerode` to version 2.2.2 (latest), the problem seems to be solved.
I will create a pull request later on.
