### ISSUE TITLE
Pull an image (without group UI) on setected daemons

### ISSUE THREAD

**Issue by yesnault** [docktor/docktor#12]

**Comment by fsamin** [comment]
I'm working on this issue :
On Service edition page, i will the the list of images (active or not) and for every daemons, if the image  there or not. If not, add a button to pull it.

ping @yesnault, @sguiheux , @gwleclerc 
I would also add a new brand feature to docktor, we could connect docktor to a registry and so be able to declare a service by picking a image directly from the registry known images and then pull images to every daemons.
So we would have to connect docktor tho the registry API.

If it's fine for your i will create a new issue to the roadmap.

**Comment by yesnault** [comment]
Ok for me. Not one, but one or many regristries

Le samedi 14 mars 2015, François Samin <notifications@github.com> a écrit :

> I'm working on this issue :
> On Service edition page, i will the the list of images (active or not) and
> for every daemons, if the image there or not. If not, add a button to pull
> it.
>
> ping @yesnault <https://github.com/yesnault>, @sguiheux
> <https://github.com/sguiheux> , @gwleclerc <https://github.com/gwleclerc>
> I would also add a new brand feature to docktor, we could connect docktor
> to a registry and so be able to declare a service by picking a image
> directly from the registry known images and then pull images to every
> daemons.
> So we would have to connect docktor tho the registry API.
>
> If it's fine for your i will create a new issue to the roadmap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docktor/docktor/issues/12#issuecomment-80411482>.
>


-- 
--
Yvonnick Esnault
yvonnick@esnau.lt - http://github.com/yesnault

**Comment by fsamin** [comment]
:+1:

**Comment by sguiheux** [comment]
Gogogo
