### ISSUE TITLE
Grant Group Users to add/remove other to their own Group

### ISSUE THREAD

**Issue by fsamin** [docktor/docktor#57]
- [x] Admin ->  add a new param on user : "can add contact"
- [ ] User -> View Group, add a new action for role="user can add contact" and role=admin : add a new contact

**Comment by yesnault** [comment]
- [ ] Admin ->  add a new param on user : "can add contact"
- [ ] User -> View Group, add a new action for role="user can add contact" and role=admin : add a new contact
