### ISSUE TITLE
Impossible to restore user password

### ISSUE THREAD

**Issue by iMax-pp** [docktor/docktor#75]
On page `/#!/password/forgot`,
- Enter a Username
- Click on Restore
- Then nothing happens

The JS console has the error `POST http://xxx/auth/forgot 500 (Internal Server Error)`.

**Comment by yesnault** [comment]
Do you have anything in the log file ? Mailer is configured in conf file ?

**Comment by iMax-pp** [comment]
Nothing much in the log file:
```
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

As for the mailer in conf file, it is based on environment variables:
```js
mailer: {
    from: process.env.MAILER_FROM || 'MAILER_FROM',
    options: {
        service: process.env.MAILER_SERVICE_PROVIDER || 'MAILER_SERVICE_PROVIDER',
        auth: {
            user: process.env.MAILER_EMAIL_ID || 'MAILER_EMAIL_ID',
            pass: process.env.MAILER_PASSWORD || 'MAILER_PASSWORD'
        }
    }
}
```
And they don't seem to be set up. So it might be the problem.

**Comment by yesnault** [comment]
That's probably the problem... Can I close this issue ?

**Comment by iMax-pp** [comment]
This was in fact the problem.
Unfortunately for me, no email address was configured for this account...
