### ISSUE TITLE
Feature : Change Environment Variables on running services

### ISSUE THREAD

**Issue by fsamin** [docktor/docktor#77]
Add ability to override env. variables on running services (ie.g. redefine HTTP_PROXY settings)

**Comment by yesnault** [comment]
Hum... Override env without redeploy or restarting service in containers, I'm not sure if it's possible.
But : 
 - At deploy : you can now, from yesterday, update env variable inherits from Docktor Group or Daemon or service, or add new env, port, fs too.
 - with a stop / start (without remove container): I think it's not possible with docker

And needs of https://github.com/docktor/docktor/issues/9 have to be clearly redefined

**Comment by fsamin** [comment]
Hum... (bis)
 - At Deploy that't great if we can now override env variables
 - with a stop / start, without remove container:  it will be great. I will check in docker and may had an issue.

fu***ng proxy (you know what i mean !)

**Comment by fsamin** [comment]
Unfortunately, Docker defines env. variables on "docker create" only... So, I close this issue.
