### ISSUE TITLE
No filesystem listed on group edition page

### ISSUE THREAD

**Issue by iMax-pp** [docktor/docktor#78]
When editing a group to add a filesystem, after selecting the daemon, only the description field is displayed and no choice is available for the filesystem.

No error is logged in the JS console.
The queries to `/daemons/docker/infos/xxx` and `/daemons/docker/stats/xxx` return with meaningful data.

**Comment by iMax-pp** [comment]
Issue fixed with pull request #94.

**Comment by fsamin** [comment]
:+1:
